spring:
  application:
    name: consul-consumer
  profiles:
    active: dev
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        # 服务名称
        service-name: ${spring.application.name}

server:
  port: 80

logging:
  file:
    name: /log/cloud-demo/${spring.application.name}${server.port}.log
