spring:
  application:
    name: hystrix-provider
  profiles:
    active: dev

server:
  port: 8080

eureka:
  instance:
    # 修改服务名称
    instance-id: ${spring.application.name}${server.port}
    # 显示IP地址
    prefer-ip-address: true
  client:
    # 是否注册(自己是客户端，需要)
    register-with-eureka: true
    # 是否需要检索服务(服务端是集群模式，需要)
    fetch-registry: true
    # 服务端地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

logging:
  file:
    name: /log/cloud-demo/${spring.application.name}${server.port}.log

