spring:
  application:
    name: feign-consumer
  profiles:
    active: dev

server:
  port: 80

eureka:
  instance:
    # 修改服务名称
    instance-id: ${spring.application.name}${server.port}
    # 显示IP地址
    prefer-ip-address: true
#    # 每1秒钟发送一次心跳报文
#    lease-renewal-interval-in-seconds: 1
#    # 超过2秒钟未发送报文将被剔除
#    lease-expiration-duration-in-seconds: 2
  client:
    # 是否注册(自己是客户端，需要)
    register-with-eureka: true
    # 是否需要检索服务(服务端是集群模式，需要)
    fetch-registry: true
    # 服务端地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

# 设置feign客户端超时时间(openfeign默认支持ribbon)
ribbon:
  # 建立连接超时时间(毫秒)
  ReadTimeout: 5000
  # 建立连接后从服务器读取可用资源时间(毫秒)
  ConnectTimeout: 5000

# 配置feign日志等级
# NONE：不显示(默认)
# BASIC：请求方法、URL、状态码、执行时间
# HEADERS：BASIC、请求头、响应头
# FULL：HEADERS、请求体、响应体、元数据
feign:
  client:
    config:
      default:
        loggerLevel: FULL

logging:
  file:
    name: /log/cloud-demo/${spring.application.name}${server.port}.log
  level:
    # 修改feign接口日志输出为debug模式
    com.demo.service.PaymentFeignService: debug
